services:
  console.loaditemstagscommand:
    class: System\Console\Command\LoadItemsTags\LoadItemsTagsCommand
    calls:
      - [setLogger, ['@logger']]
      - [setBillingComponent, ['@component.billing']]
      - [setFlashNotice, ['@component.flashNotice']]
      - [setItemsTagsRepository, ['@repository.itemsTags']]