services:
  console.payservice:
    class: System\Console\Service\Pay\PayService
    calls:
    - [setLogger, ['@logger']]
    - [setBillingComponent, ['@component.billing']]
    - [setChatsRepository, ['@repository.chats']]
    - [setPayBot, ['@telegram.payPot']]
    - [setPaymentsRepository, ['@repository.payments']]
    - [setDaemonComponent, ['@component.daemon']]
    - [setStagesMessagesRepository, ['@repository.stagesMessages']]
    - [setPaymentsPrintDataRepository, ['@repository.paymentsPrintData']]
    - [setChatsHistoryRepository, ['@repository.chatsHistory']]
    - [setMessageProcessingComponent, ['@component.messageProcessing']]